### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by Blacksmithov** [DanielOliver/mssql_exporter#21]
When starting 70 metrics during debugging, an error appears:
```Hosting environment: Production

Content root path: C:\mssql_exporter

Now listening on: http://[::]:83

Application started. Press Ctrl+C to shut down.

[18:59:04 DBG] Connection id "0HM7GBT8HPG0E" accepted.

[18:59:04 DBG] Connection id "0HM7GBT8HPG0E" started.

[18:59:04 INF] Request starting HTTP/1.1 GET http://localhost:83/metrics

[18:59:04 DBG] Wildcard detected, all requests with hosts will be allowed.

[18:59:34 ERR] Query fastpayments_transactions_total failed

System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

---> System.ComponentModel.Win32Exception (258): The wait operation timed out.

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()

   at System.Data.SqlClient.SqlDataReader.get_MetaData()

   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)

   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)

   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)

   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)

   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)

   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)

   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)

   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)

   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)

   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)

   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 39

ClientConnectionId:1541ed4e-b3c8-4009-8693-c3f9f246c257

Error Number:-2,State:0,Class:11
```

Application launch:
```
mssql_exporter.exe serve -ConfigFile "metrics.json" -DataSource "Server=tcp:localhost,1433;Initial Catalog=dbname;Persist Security Info=False;User ID=userdb;Password=blablabla;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=False;Connection Timeout=600;" -ServerPort 83 -LogLevel Debug
```
MillisecondTimeout parameter: 60000

Why is there a timeout?
Feeling that the timeout is 30 seconds

**Comment by Blacksmithov** [comment]
im add timeout in QueryExtensions.cs
```
using (var command = new SqlCommand(query.Query, sqlConnection))
							{
								command.CommandTimeout = defaultMillisecondTimeout/1000;
```
