### ISSUE TITLE
Connect failed

### ISSUE THREAD

**Issue by Freel-Freel** [DanielOliver/mssql_exporter#6]
Thank You for Your work on this Exporter!
I am working with your product and i have the following problem with it, if You will be able to help me, i will appreciate it.

Try to start:
```
/home/monitoring/monitoring/bin/mssql_exporter/mssql_exporter \
serve -ServerPort 18080 -ServerPath /metrics -AddExporterMetrics True \
-ConfigFile "/home/monitoring/monitoring/conf/mssql_exporter/mssql_exporter.json" \
-DataSource "Server=tcp:10.20.2.103,1433;Initial Catalog=master;Persist Security Info=False;User ID=monitoring;Password=monitoring;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
```

Console output:
```
Hosting environment: Production
Content root path: /home/monitoring/monitoring
Now listening on: http://[::]:18080
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://172.30.168.33:18080/metrics
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 885.6413ms 200 text/plain; version=0.0.4
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://172.30.168.33:18080/metrics
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.9955ms 200 text/plain; version=0.0.4
```

Exporter http:
```
# HELP mssql_timeouts Number of queries timing out.
# TYPE mssql_timeouts gauge
mssql_timeouts 0
# HELP mssql_deadlocks mssql_deadlocks
# TYPE mssql_deadlocks gauge
mssql_deadlocks 0
# HELP mssql_up mssql_up
# TYPE mssql_up gauge
mssql_up 0
# HELP mssql_exceptions Number of queries throwing exceptions.
# TYPE mssql_exceptions gauge
mssql_exceptions 3
# HELP mssql_process_status Counts the number of processes per status
# TYPE mssql_process_status gauge
```

The problem is: when Exporter connecting with MSSQL, i got the following error:
```
mssql_up 0
```
How can i turn on the debug mode ?

**Comment by alexd88** [comment]
>
> How can i turn on the debug mode ?

It's easy enough:
```
#> ./mssql_exporter server -LogLevel Debug -DataSource 'Server=....'
```

**Comment by alexd88** [comment]
I highly likely have come across the same issue.

```
[root@monitoring]# ./mssql_exporter serve -DataSource 'Server=tcp:xx.aa.bb.cc,1433;User ID=stat;Password=SuperDuperSecretPassword;Initial Catalog=master;Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=False;Tru
stServerCertificate=False;Connection Timeout=1000;' -ServerPort 9444 -LogLevel Debug
```

I see this messages:
```
[17:36:36 INF] ServerPath metrics; ServerPort 9444; AddExporterMetrics False; LogLevel Debug
[17:36:36 INF] Reading ConfigText {
    "Queries": [
        {
            "Name": "mssql_process_status",
            "Query": "SELECT status, COUNT(*) count FROM sys.sysprocesses GROUP BY status",
            "Description": "Counts the number of processes per status",
            "Usage": "GaugesWithLabels",
            "Columns": [
                {
                    "Name": "status",
                    "Label": "status",
                    "Usage": "GaugeLabel",
                    "Order": 0
                },
                {
                    "Name": "count",
                    "Label": "count",
                    "Usage": "Gauge"
                }
            ]
        },
        {
            "Name": "mssql_deadlocks",
            "Query": "SELECT cntr_value FROM sys.dm_os_performance_counters where counter_name = 'Number of Deadlocks/sec' AND instance_name = '_Total'",
            "Description": "Number of lock requests per second that resulted in a deadlock since last restart",
            "Columns": [
                {
                    "Name": "cntr_value",
                    "Label": "mssql_deadlocks",
                    "Usage": "Gauge",
                    "DefaultValue": 0
                }
            ]
        },
        {
            "Name": "mssql_select1",
            "Query": "SELECT 1",
            "Description": "select1",
            "Columns": [
                {
                    "Name": "cntr_value",
                    "Label": "mssql_select1",
                    "Usage": "Gauge",
                    "DefaultValue": 0
                }
            ]
        }

    ],
    "MillisecondTimeout": 10000
} from metrics.json
[17:36:36 INF] Creating metric mssql_process_status
[17:36:36 INF] Creating metric mssql_deadlocks
[17:36:36 INF] Creating metric mssql_select1
[17:36:36 DBG] Hosting starting
[17:36:36 DBG] Failed to locate the development https certificate at 'null'.
[17:36:36 DBG] Hosting started
[17:36:36 DBG] Loaded hosting startup assembly mssql_exporter
Hosting environment: Production
Content root path: /opt/mssql_exporter/linux_x64
Now listening on: http://[::]:9444
Application started. Press Ctrl+C to shut down.
```

Then i send a request and get a response:
```
[root@monitoring ~]# http :9444/metrics
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Tue, 11 Feb 2020 14:39:36 GMT
Server: Kestrel
Transfer-Encoding: chunked

# HELP mssql_exceptions Number of queries throwing exceptions.
# TYPE mssql_exceptions gauge
mssql_exceptions 4
# HELP mssql_select1 mssql_select1
# TYPE mssql_select1 gauge
mssql_select1 0
# HELP mssql_up mssql_up
# TYPE mssql_up gauge
mssql_up 0
# HELP mssql_deadlocks mssql_deadlocks
# TYPE mssql_deadlocks gauge
mssql_deadlocks 0
# HELP mssql_timeouts Number of queries timing out.
# TYPE mssql_timeouts gauge
mssql_timeouts 0
# HELP mssql_process_status Counts the number of processes per status
# TYPE mssql_process_status gauge
```

All of 4 requests failed ((

I observe in mssql_exporter output messages:
```
[17:39:36 DBG] Connection id "0HLTF00RSMGKK" accepted.
[17:39:36 DBG] Connection id "0HLTF00RSMGKK" started.
[17:39:36 INF] Request starting HTTP/1.1 GET http://localhost:9444/metrics
[17:39:36 DBG] Wildcard detected, all requests with hosts will be allowed.
[17:39:36 ERR] Query mssql_process_status failed
System.InvalidOperationException: Internal connection fatal error.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&
connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
[17:39:36 ERR] Query mssql_select1 failed
System.InvalidOperationException: Internal connection fatal error.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&
connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
[17:39:36 ERR] Query mssql_deadlocks failed
System.InvalidOperationException: Internal connection fatal error.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&
connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
[17:39:36 ERR] Query mssql_up failed
System.InvalidOperationException: Internal connection fatal error.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
   at mssql_exporter.core.QueryExtensions.<>c__DisplayClass0_0.<MeasureWithConnection>b__0() in /home/vsts/work/1/s/src/core/QueryExtensions.cs:line 26
[17:39:36 DBG] Connection id "0HLTF00RSMGKK" completed keep alive response.
[17:39:36 INF] Request finished in 218.726ms 200 text/plain; version=0.0.4; charset=utf-8
[17:39:36 DBG] Connection id "0HLTF00RSMGKK" received FIN.
[17:39:36 DBG] Connection id "0HLTF00RSMGKK" sending FIN because: "The client closed the connection."
[17:39:36 DBG] Connection id "0HLTF00RSMGKK" disconnecting.
[17:39:36 DBG] Connection id "0HLTF00RSMGKK" stopped.
```

At the same time when i test mssql exporter with docker-compose.yml included in repository it works excellent.

@DanielOliver i guess we need your assistance)

I'm looking forward to your reply

PS
MSSQL Version: Microsoft SQL Server 2016 (SP2-CU5) (KB4475776) - 13.0.5264.1 (X64)

**Comment by alexd88** [comment]
Fix in my case:

Change `System.Globalization.Invariant` to **false**  in _mssql_exporter.runtimeconfig.json_

```
{
  "runtimeOptions": {
    ...
    "configProperties": {
      "System.Globalization.Invariant": false,
      ...
    }
  }
}
```

**Comment by kernelpanic01** [comment]
Hi. This is mi metrics.json

{
    "Queries": [
        {
            "Name": "mssql_process_status",
            "Query": "Select SbookID,COUNT(*) Counter FROM Doughflow.dbo.vwUnifiedTransactions Group by SbookID",
            "Description": "Counts the number of Deposit Attempt by Brand",
            "Columns": [
                {
                    "Name": "SbookID",
                    "Label": "SbookID",
                    "Usage": "GaugeLabel",
                },
                {
                    "Name": "Counter",
                    "Label": "Counter",
                    "Usage": "CounterLabel"
                }
            ]
        }
        ],
    "MillisecondTimeout": 4000
}

and startup mi server :
./mssql_exporter serve -LogLevel Debug -ConfigFile "metrics_test.json" -DataSource "Server=tcp:REPORTDB02.DEVELOPMENT.DOM,1433;Initial Catalog=Common;Persist Security Info=False;User ID=basExporterUser;Password=iwuY8b33bd;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=False;Connection Timeout=8;" -ServerPort 9095


This is the log:

root@dev-ptybas01:/opt/mssql_exporter# ./mssql_exporter serve -LogLevel Debug -ConfigFile "metrics_test.json" -DataSource "Server=tcp:REPORTDB02.DEVELOPMENT.DOM,1433;Initial Catalog=Common;Persist Security Info=False;User ID=basExporterUser;Password=iwuY8b33bd;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=False;Connection Timeout=8;" -ServerPort 9095
[14:49:17 INF] ServerPath metrics; ServerPort 9095; AddExporterMetrics False; LogLevel Debug
[14:49:17 INF] Reading ConfigText {
    "Queries": [
        {
            "Name": "mssql_bas_metrics",
            "Query": "Select SbookID,COUNT(*) Counter FROM Doughflow.dbo.vwUnifiedTransactions Group by SbookID",
            "Description": "Counts the number of Deposit Attempt by Brand",
            "Columns": [
                {
                    "Name": "SbookID",
                    "Label": "SbookID",
                    "Usage": "GaugeLabel",
                },
                {
                    "Name": "Counter",
                    "Label": "Counter",
                    "Usage": "CounterLabel"
                }
            ]
        }
        ],
    "MillisecondTimeout": 4000
}
 from metrics_test.json
[14:49:17 INF] Creating metric mssql_bas_metrics
[14:49:17 DBG] Hosting starting
[14:49:17 DBG] Failed to locate the development https certificate at 'null'.
[14:49:17 DBG] Hosting started
[14:49:17 DBG] Loaded hosting startup assembly mssql_exporter
Hosting environment: Production
Content root path: /opt/mssql_exporter
Now listening on: http://[::]:9095
Application started. Press Ctrl+C to shut down.
[14:49:29 DBG] Connection id "0HLV0NMQSPAMC" accepted.
[14:49:29 DBG] Connection id "0HLV0NMQSPAMC" started.
[14:49:30 INF] Request starting HTTP/1.1 GET http://localhost:9095/metrics
[14:49:30 DBG] Wildcard detected, all requests with hosts will be allowed.
[14:49:30 DBG] Connection id "0HLV0NMQSPAMC" completed keep alive response.
[14:49:30 INF] Request finished in 733.8008ms 200 text/plain; version=0.0.4; charset=utf-8
[14:49:44 INF] Request starting HTTP/1.1 GET http://localhost:9095/metrics
[14:49:45 DBG] Connection id "0HLV0NMQSPAMC" completed keep alive response.
[14:49:45 INF] Request finished in 124.4885ms 200 text/plain; version=0.0.4; charset=utf-8
[14:49:59 INF] Request starting HTTP/1.1 GET http://localhost:9095/metrics
[14:50:00 DBG] Connection id "0HLV0NMQSPAMC" completed keep alive response.
[14:50:00 INF] Request finished in 97.2701ms 200 text/plain; version=0.0.4; charset=utf-8
[14:50:14 INF] Request starting HTTP/1.1 GET http://localhost:9095/metrics
[14:50:15 DBG] Connection id "0HLV0NMQSPAMC" completed keep alive response.
[14:50:15 INF] Request finished in 83.0529ms 200 text/plain; version=0.0.4; charset=utf-8


BUT i can´t see the metrics en localhost:9095. Only view the:
# HELP mssql_up mssql_up
# TYPE mssql_up gauge
mssql_up 1
# HELP mssql_timeouts Number of queries timing out.
# TYPE mssql_timeouts gauge
mssql_timeouts 0
# HELP mssql_exceptions Number of queries throwing exceptions.
# TYPE mssql_exceptions gauge
mssql_exceptions 0

Why i can´t see the mssql_bas_metrics?

**Comment by Mario-Hofstaetter** [comment]
@alexd88 has this been fixed by #11 ?
